modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/SamsTheNerd/ducky-periphs/issues"
showAsResourcePack = false

[[mods]]
modId = "wnboi"
version = "${version}"
displayName = "Why Not Be One Item"
authors = "samsthenerd"
description = '''
A library mod for context menus
'''
logoFile = "IconWNBOI.png"

[[dependencies.wnboi]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wnboi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"